### ISSUE TITLE
你也许可以用一用糖糕云的服务器

### ISSUE THREAD

**Issue by hamiguatang** [YuShanNan/ChiLing-HomePage-PCL2#1]
这个服务器的虚拟主机搭在香港，不需要很多的设置就可以作为联网更新的使用，就比如说仕洋的主页SYC
http://gluvsf.mcfuns.cn/Custom.xaml
这是糖糕云的链接
https://cloud.tanggaoyun.cn/aff/BNKXQFJH

**Comment by YuShanNan** [comment]
好的，我试试看，谢谢了

**Comment by YuShanNan** [comment]
坏了，我开通了虚拟主机，但我不知道如何操作QWQ

**Comment by YuShanNan** [comment]
坏了，我还是不懂怎么操作QWQ

**Comment by hamiguatang** [comment]
挺好搞的，买完以后把Custom.xaml上传到根目录，Custom.xaml.ini也上传到根目录就行了

**Comment by YuShanNan** [comment]
http://hk1.xlhost.cn/Custom.xaml
我不确定它能使用(未添加 Custom.xaml.ini)
电脑不在身边

**Comment by YuShanNan** [comment]
http://hk1.xlhost.cn/Custom.xaml
我不确定它能使用(未添加 Custom.xaml.ini)
电脑不在身边

**Comment by hamiguatang** [comment]
越看越熟悉，这不是管理的网页吗，是这个右下角的主机名称
![image](https://github.com/YuShanNan/ChiLing-HomePage-PCL2/assets/143095655/fd4f241e-a7ce-463e-8ec0-daa65daaf753)

**Comment by YuShanNan** [comment]
没找到啊😦，我买的Easypanel面板_(´□`」 ∠)_

**Comment by hamiguatang** [comment]
![image](https://github.com/YuShanNan/ChiLing-HomePage-PCL2/assets/143095655/d396bcc0-98bc-42c9-8808-2a7a5486065e)
通常都是http://(这里是FTP或数据库账号).mcfuns.cn

**Comment by YuShanNan** [comment]
可是我的ftp账号或数据库账号，和面板账号是同一个_(´ཀ`」 ∠)__ ，无法访问

**Comment by YuShanNan** [comment]
我直接重新买一个宝塔面板的吧（
